### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by 01315794284** [01315794284/sec#1]
- [ ] Mudar os links da internet para links locais 
- [ ] Criar o menu DEL 
- [ ] Criar o menu EDITAR 
- [ ] Criar o menu DEL 
- [ ] Forçar validação de campos em adicionar aluno - Opções pré definidas (Quadro/Sexo...) 
- [ ] Listar usuários cadastrados 
- [ ] Criar nível de acesso para alunos 
- [ ] Criar painel de visualização e CRUD para aluno
- [ ] Colocar em 1 BD apenas?
